version: '3.8'

services:
  rentify-app:
    build:
      context: .
      target: production
    env_file: .env
    environment:
      - NODE_ENV=production
  postgres-db:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d rentify_prod" ]
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      POSTGRES_DB: rentify_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: open1234