version: '3.8'

services:
  rentify-app:
    image: mostafahamzawy/rentify
    ports:
      - "4000:3000"
    container_name: rentify_container
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    networks:
      - my-net
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  postgres-db:
    image: postgres:16
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: rentify_db
    networks:
      - my-net
  redis:
    image: redis:7
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    container_name: rentify_cache_redis
    restart: always
    ports:
      - '6380:6379'
    networks:
      - my-net

volumes:
  pgdata:

networks:
  my-net: